language: node_js
node_js:
- node
notifications:
  slack:
    secure: mwz2SWuOwQOmBaRXkUg5BWmxeKrrOI/o3uwQhCNwcIMViRZeSxulJn2aG7ztL4BjYydSDxBLXsodmtCkmtx7GMUImqj0jT3IMJNLOJGfq7o19dx97H9jeLOHRbV9leUItFXPEfVSVYrRy/9F4qt9TrxW+MG5z4i9ZanH+/6bptz7njl//ysgIbHFwP05OcfP40qez7x6tEeIBZKlaMBqJu9Irmg38aTGT+pb7aC+usNxSMNUDa/npY+MvkNLSPG4L3JyI+MOYM2DjMn4xGMxBS/uOlEqgK9ai6NRNVNBBkDPDIXSBI2IP/2o26PEZvBQusQuDrB4pL6tLbZOnbMy5tUJk1eLCoDC4IQGcd4nMTwzJu9a2lYMcyAL6QpdjFnkYJiNsBpdBxgBzg9SDTOEQEZ4e9nKLOSiZEm8odJP8LXoDbMl5glAVuL73VsPn2WGl5wM829/nbi4zVRXqdH7FxY4C4t0HRHtw0bqhViDpG9MXw+Lo9ePgoKzHLV40rKP+6nLD4OT54QepHQYxn6pLC3s4zihbJ1eQ4zdiNwq7LOu2hZ+VKh6U4CUimGwjXNTIIwf/dpI2lBs+ioXb22E794R4g1wB5RaDfPPkqx5YOB8G4V+TP/e9lbiYitGPEn6VkgrLAbBRR/bJwUDUy5l65OAzIyJdvPiMwK54b3vQxQ=
